<?php
$title = "东北师范大学第七届ACM/ICPC程序设计竞赛 - 网络赛排名";
include_once('header.inc.php');?>
<table class="table table-striped table-bordered table-condensed tablesorter">
<thead>
<tr><th>Rank</th><th>Name</th><th>Sloved</th><th>Penalty</th><th>Department</th><th>Major</th><th>Grade</th><th>Gender</th></tr>
</thead>
<tbody>
<tr><td>1</td><td>杨晟雨</td><td>11</td><td>741</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>2</td><td>王建丰</td><td>10</td><td>713</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>3</td><td>杨带怡</td><td>10</td><td>714</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>4</td><td>刘雨林</td><td>10</td><td>739</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>5</td><td>张权</td><td>10</td><td>1019</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>6</td><td>张文怡</td><td>10</td><td>1218</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>女</td></tr>
<tr><td>7</td><td>叶健</td><td>9</td><td>304</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>8</td><td>张利刚</td><td>9</td><td>334</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>9</td><td>颜瑶</td><td>9</td><td>408</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>10</td><td>郭小兵</td><td>9</td><td>622</td><td>软件学院</td><td>软件</td><td>2011</td><td>男</td></tr>
<tr><td>11</td><td>李淼洋</td><td>9</td><td>729</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>12</td><td>李久旸</td><td>9</td><td>861</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>男</td></tr>
<tr><td>13</td><td>周擎</td><td>9</td><td>947</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>14</td><td>向黎</td><td>9</td><td>950</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>15</td><td>周姝君</td><td>9</td><td>1030</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>16</td><td>张昂</td><td>9</td><td>1053</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>17</td><td>何涛</td><td>9</td><td>1070</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>18</td><td>高鑫</td><td>8</td><td>369</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>19</td><td>程仁操</td><td>8</td><td>398</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>20</td><td>李芳林</td><td>8</td><td>417</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>21</td><td>郭家祯</td><td>8</td><td>464</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>22</td><td>赵宵飒</td><td>8</td><td>482</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>23</td><td>王天宇</td><td>8</td><td>482</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>24</td><td>陶胜</td><td>8</td><td>514</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>25</td><td>孙焕垚</td><td>8</td><td>538</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>26</td><td>严一格</td><td>8</td><td>777</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>27</td><td>王博瑶</td><td>8</td><td>784</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>28</td><td>李齐鹏</td><td>8</td><td>880</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>男</td></tr>
<tr><td>29</td><td>张书宜</td><td>8</td><td>936</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>30</td><td>汤树林</td><td>8</td><td>1047</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>31</td><td>华希希</td><td>8</td><td>1071</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>32</td><td>康赟</td><td>7</td><td>318</td><td>计算机科学与信息技术学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>33</td><td>姜璐</td><td>7</td><td>414</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>34</td><td>乔羽</td><td>7</td><td>640</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>女</td></tr>
<tr><td>35</td><td>胡正阳</td><td>7</td><td>646</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>男</td></tr>
<tr><td>36</td><td>桂欣</td><td>7</td><td>658</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>37</td><td>张树恒</td><td>7</td><td>664</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>38</td><td>朱明一</td><td>7</td><td>669</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>39</td><td>马超</td><td>7</td><td>712</td><td>地理科学学院</td><td>自然地理学</td><td>2012</td><td>男</td></tr>
<tr><td>40</td><td>崔继运</td><td>7</td><td>754</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2010</td><td>男</td></tr>
<tr><td>41</td><td>蔡永健</td><td>7</td><td>774</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>42</td><td>包玲玲</td><td>7</td><td>814</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>43</td><td>吴家杰</td><td>7</td><td>840</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>44</td><td>朱佐浪</td><td>7</td><td>910</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>45</td><td>夏蓝谱</td><td>7</td><td>951</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>46</td><td>高晨龙</td><td>7</td><td>952</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>47</td><td>谭福达</td><td>7</td><td>989</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>48</td><td>刘扬</td><td>7</td><td>1005</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>49</td><td>曲峥</td><td>7</td><td>1038</td><td>计算机科学与信息技术学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>50</td><td>马宇驰</td><td>7</td><td>1079</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>51</td><td>杨镇宁</td><td>7</td><td>1203</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>52</td><td>张侃</td><td>7</td><td>1230</td><td>软件学院</td><td>软件学院</td><td>2012</td><td>男</td></tr>
<tr><td>53</td><td>张芃</td><td>7</td><td>1240</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>54</td><td>李倩</td><td>7</td><td>1241</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>55</td><td>赵嘉</td><td>7</td><td>1318</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>56</td><td>胡凯文</td><td>7</td><td>1342</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>57</td><td>冯朝兵</td><td>7</td><td>1418</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>58</td><td>杨天羡</td><td>7</td><td>1444</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>59</td><td>刘笑</td><td>7</td><td>1693</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>60</td><td>牛秀南</td><td>6</td><td>349</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>61</td><td>蒲蕾</td><td>6</td><td>364</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>女</td></tr>
<tr><td>62</td><td>尹宗铭</td><td>6</td><td>476</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>63</td><td>蒋坤</td><td>6</td><td>498</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>64</td><td>陈一凡</td><td>6</td><td>606</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>65</td><td>黎佑民</td><td>6</td><td>640</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>66</td><td>唐君健</td><td>6</td><td>661</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>男</td></tr>
<tr><td>67</td><td>张亚飞</td><td>6</td><td>705</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>68</td><td>王迪</td><td>6</td><td>712</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>男</td></tr>
<tr><td>69</td><td>邵荟洁</td><td>6</td><td>717</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2011</td><td>女</td></tr>
<tr><td>70</td><td>崔元</td><td>6</td><td>759</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>女</td></tr>
<tr><td>71</td><td>张元曈</td><td>5</td><td>84</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>男</td></tr>
<tr><td>72</td><td>刘雨丹</td><td>5</td><td>306</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>73</td><td>周筱婕</td><td>5</td><td>474</td><td>软件学院</td><td>软件工程</td><td>2011</td><td>女</td></tr>
<tr><td>74</td><td>陈嘉炜</td><td>5</td><td>513</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>75</td><td>刘伊斯</td><td>5</td><td>590</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>76</td><td>徐晓青</td><td>5</td><td>593</td><td>计算机科学与信息技术学院</td><td>教育技术学</td><td>2012</td><td>女</td></tr>
<tr><td>77</td><td>张金玲</td><td>5</td><td>762</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>78</td><td>徐桂萍</td><td>5</td><td>834</td><td>计算机科学与信息技术学院</td><td>计算机科学与技术</td><td>2012</td><td>女</td></tr>
<tr><td>79</td><td>黄轩峰</td><td>4</td><td>86</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>80</td><td>欧阳猛</td><td>4</td><td>289</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>81</td><td>李悦</td><td>4</td><td>601</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>82</td><td>林美红</td><td>4</td><td>815</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>83</td><td>王欣茹</td><td>3</td><td>62</td><td>计算机科学与信息技术学院</td><td>教育技术学</td><td>2012</td><td>女</td></tr>
<tr><td>84</td><td>梁炳坤</td><td>3</td><td>165</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>85</td><td>王沛琪</td><td>3</td><td>197</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>女</td></tr>
<tr><td>86</td><td>钟志炜</td><td>3</td><td>229</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>87</td><td>华成玲</td><td>3</td><td>265</td><td>计算机科学与信息技术学院</td><td>教育技术学</td><td>2012</td><td>女</td></tr>
<tr><td>88</td><td>赵鑫</td><td>3</td><td>311</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>89</td><td>邵自强</td><td>3</td><td>326</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>90</td><td>马嘉男</td><td>3</td><td>351</td><td>软件学院</td><td>信息与软件工程学院</td><td>2012</td><td>女</td></tr>
<tr><td>91</td><td>赵文利</td><td>2</td><td>303</td><td>地理科学学院</td><td>地理信息系统</td><td>2011</td><td>男</td></tr>
<tr><td>92</td><td>蒲荣龙</td><td>1</td><td>3</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>93</td><td>李世操</td><td>1</td><td>35</td><td>软件学院</td><td>软件学院</td><td>2010</td><td>男</td></tr>
<tr><td>94</td><td>杜娟</td><td>1</td><td>63</td><td>软件学院</td><td>软件工程</td><td>2010</td><td>女</td></tr>
<tr><td>95</td><td>韩宇茹</td><td>1</td><td>318</td><td>计算机科学与信息技术学院</td><td>教育技术学</td><td>2012</td><td>女</td></tr>
<tr><td>96</td><td>朱佐浪</td><td>0</td><td>0</td><td>软件学院</td><td>软件工程</td><td>2012</td><td>男</td></tr>
<tr><td>97</td><td>李宁</td><td>0</td><td>0</td><td>物理学院</td><td>物理学</td><td>2010</td><td>男</td></tr>
</tbody>
</table>
<script src='js/jquery.tablesorter.min.js'></script>
<script>
$("table").addClass("tablesorter");
$("table").tablesorter({sortLocaleCompare:true});
$("th").attr("style","cursor:pointer;");
</script>

<?php
if(isset($_GET['message'])){
	echo "<script>$(function(){showMessage('" . $_GET['message'] . "');});</script>";
} 

include_once('footer.inc.php');




